image:
  file: .gitpod.dockerfile

tasks:
  - command: |
      mkdir -p /home/gitpod/.android
      touch /home/gitpod/.android/repositories.cfg
      export PATH=/usr/lib/dart/bin:$FLUTTER_HOME/bin:$ANDROID_HOME/bin:$PATH
      /home/gitpod/android-sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3"
  - init_aptos:
      command: |
        curl -fsSL "https://aptos.dev/scripts/install_cli.py" | python3
        cd move/  # Adjust the path if needed
        aptos init --network devnet
        aptos move compile
        aptos move publish

vscode:
  extensions:
    - Dart-Code.flutter
    - Dart-Code.dart-code
    - JuanBlanco.solidity
