[package]
name = "DNuV"
version = "1.0.0"
authors = []

[addresses]
my_addrx="441f651105e97958705fc6dced7ab405bef0edd13b78da6e5cc837e679122303"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
